#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32000
#SBATCH --time=72:00:00
#SBATCH --job-name=visualqc_freesurfer
#SBATCH --account=ctb-akhanf
#SBATCH --output=/scratch/myousif9/snakemake_hippocampal_unfolding/jobs/visualqc_freesurfer.%A.out
echo CMD: visualqc_freesurfer --fs_dir /home/myousif9/scratch/DM2_fmriprep/freesurfer/ --out_dir /home/myousif9/scratch/visualqc_freesurfer
echo START_TIME: `date`
cd /home/myousif9/scratch/snakemake_hippocampal_unfolding
visualqc_freesurfer --fs_dir /home/myousif9/scratch/DM2_fmriprep/freesurfer/ --out_dir /home/myousif9/scratch/visualqc_freesurfer
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
